// Generated by CoffeeScript 2.3.2
(function() {
  var color1, color2, color3, colorElements, dateElement, expElement, fullOpacity, gradientBtm, gradientTop, inputColor1, inputColor2, inputColor3, inputGradient, monthNames, setOpacityTo0, setOpacityTo1, timeConfig, timeElement, timeLimit, weekdays;

  timeConfig = {
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric',
    hour12: true
  };

  weekdays = new Array(7);

  weekdays[0] = 'Sunday';

  weekdays[1] = 'Monday';

  weekdays[2] = 'Tuesday';

  weekdays[3] = 'Wednesday';

  weekdays[4] = 'Thursday';

  weekdays[5] = 'Friday';

  weekdays[6] = 'Saturday';

  monthNames = new Array();

  monthNames[0] = 'Jan';

  monthNames[1] = 'Feb';

  monthNames[2] = 'Mar';

  monthNames[3] = 'Apr';

  monthNames[4] = 'May';

  monthNames[5] = 'Jun';

  monthNames[6] = 'Jul';

  monthNames[7] = 'Aug';

  monthNames[8] = 'Sep';

  monthNames[9] = 'Oct';

  monthNames[10] = 'Nov';

  monthNames[11] = 'Dec';

  timeElement = document.getElementById('span-time');

  dateElement = document.getElementById('span-date');

  expElement = document.getElementById('span-expiration');

  colorElements = document.getElementsByClassName('container-color-1');

  gradientTop = document.getElementById('container-ticket-gradient-1');

  gradientBtm = document.getElementById('container-ticket-gradient-2');

  inputGradient = document.getElementById('input-gradient');

  color1 = document.getElementById('color-1');

  color2 = document.getElementById('color-2');

  color3 = document.getElementById('color-3');

  inputColor1 = document.getElementById('input-color-1');

  inputColor2 = document.getElementById('input-color-2');

  inputColor3 = document.getElementById('input-color-3');

  gradientTop.addEventListener('click', function() {
    return inputGradient.click();
  });

  gradientBtm.addEventListener('click', function() {
    return inputGradient.click();
  });

  color1.addEventListener('click', function() {
    return inputColor1.click();
  });

  color2.addEventListener('click', function() {
    return inputColor2.click();
  });

  color3.addEventListener('click', function() {
    return inputColor3.click();
  });

  inputColor1.addEventListener('change', function() {
    console.log(inputColor1.value);
    return color1.style.backgroundColor = inputColor1.value;
  });

  inputColor2.addEventListener('change', function() {
    console.log(inputColor2.value);
    return color2.style.backgroundColor = inputColor2.value;
  });

  inputColor3.addEventListener('change', function() {
    console.log(inputColor3.value);
    return color3.style.backgroundColor = inputColor3.value;
  });

  inputGradient.addEventListener('change', function() {
    console.log(inputGradient.value);
    gradientTop.style.backgroundImage = `linear-gradient(${inputGradient.value}, #fff)`;
    return gradientBtm.style.backgroundImage = `linear-gradient(#fff, ${inputGradient.value})`;
  });

  timeLimit = 150 * 60; // number of minutes to count down

  fullOpacity = true; // whether or not the colors are showing

  setOpacityTo1 = function(element) {
    return element.style.opacity = "1";
  };

  setOpacityTo0 = function(element) {
    return element.style.opacity = "0";
  };

  setInterval(function() {
    var date, dateString, day, dayString, elem, i, j, len, len1, limitHours, limitMinutes, limitSeconds, limitStrHours, limitStrMinutes, limitStrSeconds, month, now, nowString, results, results1, weekday, year;
    timeLimit--;
    date = new Date();
    now = date.toLocaleString('en-US', timeConfig);
    weekday = weekdays[date.getDay()];
    month = monthNames[date.getMonth()];
    day = date.getDate();
    year = date.getFullYear();
    nowString = now.length === 10 ? `0${now}` : `${now}`;
    dayString = `${day}`;
    if (dayString.length === 1) {
      dayString = `0${day}`;
    }
    dateString = `${weekday}, ${month} ${dayString}, ${year}`;
    // console.log nowString, '\t', dateString
    timeElement.innerHTML = nowString;
    dateElement.innerHTML = dateString;
    limitHours = Math.floor(timeLimit / 3600);
    limitMinutes = Math.floor((timeLimit / 60) - limitHours * 60);
    limitSeconds = timeLimit - limitMinutes * 60 - limitHours * 60 * 60;
    limitStrHours = `${limitHours}`;
    limitStrMinutes = `${limitMinutes}`;
    limitStrSeconds = `${limitSeconds}`;
    if (limitStrHours.length === 1) {
      limitStrHours = `0${limitStrHours}`;
    }
    if (limitStrMinutes.length === 1) {
      limitStrMinutes = `0${limitStrMinutes}`;
    }
    if (limitStrSeconds.length === 1) {
      limitStrSeconds = `0${limitStrSeconds}`;
    }
    expElement.innerHTML = `Expires in 00:${limitStrHours}:${limitStrMinutes}:${limitStrSeconds}`;
    if (fullOpacity) {
      fullOpacity = false;
      results = [];
      for (i = 0, len = colorElements.length; i < len; i++) {
        elem = colorElements[i];
        results.push(setOpacityTo0(elem));
      }
      return results;
    } else {
      fullOpacity = true;
      results1 = [];
      for (j = 0, len1 = colorElements.length; j < len1; j++) {
        elem = colorElements[j];
        results1.push(setOpacityTo1(elem));
      }
      return results1;
    }
  }, 1000);

}).call(this);
